MamGlosWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

# if settings.DEBUG is True:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name="main-home"),
    path('about/', views.about, name="main-about"),
    # path('adopted/', views.adopted, name="main-adopted"),
    path('adopted/', views.AdoptedList.as_view(), name="main-adopted"),
    path('contact/', views.contact, name="main-contact"),
    path('forAdoption/', views.ForAdoptionList.as_view(), name="main-forAdoption"),
    path('news/', views.NewsList.as_view(), name="main-news"),
    path('partner/', views.partner, name="main-partner"),
    path('support/', views.support, name="main-support"),
    path('volo/', views.volo, name="main-volo"),
    path('foundlost/', views.FoundLostList.as_view(), name="main-foundlost"),

]

main/models.py
from django.db import models
from django.utils import timezone
import os
from PIL import Image



class Dog(models.Model):
    dog_name = models.CharField(max_length=25)
    dog_description = models.TextField()
    dog_picture = models.ImageField(default='default_dog.jpg', upload_to='dogs_pics')
    dog_gallery = models.TextField(default='https://www.facebook.com/pg/stowarzyszenieMamGlos/photos/?tab=albums')
    was_adopted = models.BooleanField(default=False)
    added = models.DateTimeField(default=timezone.now, blank=True, null=True)
    adoption_date = models.DateField(default=timezone.now)

    def save(self):
        super().save()

        img = Image.open(self.dog_picture.path)
        if img.width > img.height and img.width > 750:
            output_size = (750, 500)
        else:
            output_size = (500,500)
        img.thumbnail(output_size)
        img.save(self.dog_picture.path)


    def __str__(self):
        return self.dog_name



class Employee(models.Model):
    employee_name = models.CharField(max_length=35)
    employee_picture = models.ImageField(default='personImage.png', upload_to='employees_pics')

    def __str__(self):
        return self.employee_name


class Article(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateTimeField(default=timezone.now)
    tldr = models.TextField(max_length=200)
    fb_link = models.TextField(blank=True)
    article_text = models.TextField()
    is_main_article = models.BooleanField(default=False)
    is_lost = models.BooleanField(default=False)
    is_found = models.BooleanField(default=False)
    is_support = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_main_article:
                Article.objects.filter(is_main_article=True).update(is_main_article=False)
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class ArticlePicture(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='articles_pics', blank=True)

class Partner(models.Model):
    name = models.TextField(default='nazwa')
    logo = models.ImageField(default='default_logo.jpg', upload_to='partners_pics')
    thanks_link = models.TextField(default='https://www.facebook.com/stowarzyszenieMamGlos/')

    def __str__(self):
        return self.name

class Document(models.Model):
    file = models.FileField(upload_to='documents')
    filename_str = models.CharField(max_length=50, default='plik')

    def filename(self):
        if self.filename_str is not 'plik':
            return self.filename_str
        else:
            return os.path.basename(self.file.name)

    def __str__(self):
        return os.path.basename(self.file.name)

main/views.py
from django.shortcuts import render
from .models import Dog, Employee, Article, Partner, Document
from django.views.generic.list import ListView
# from random import sample, shuffle

def home(request):
    context = {
        'articles_main':Article.objects.filter(is_main_article = True),
        'partners': Partner.objects.all(),
        'dog_count': len(Dog.objects.all()),
    }
    return render(request, 'main/index.html', context)

def about(request):
    context = {
        'employees': Employee.objects.all(),
        'documents': Document.objects.all()
    }
    return render(request, 'main/about.html', context)

class AdoptedList(ListView):
    model = Dog
    template_name = 'main/adopted.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(was_adopted=True).order_by('-adoption_date')

def contact(request):
    return render(request,'main/contact.html')

class ForAdoptionList(ListView):
    model = Dog
    template_name='main/forAdoption.html'

    def get_queryset(self):
        qs = super().get_queryset()
        # last_id = qs.objects.all[-1]
        # # random_qs = sample(qs, len(qs))
        # # return random_qs.filter(was_adopted=False)
        return qs.filter(was_adopted=False)

    def get_contex_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class NewsList(ListView):
    model = Article
    template_name = 'main/news.html'
    paginate_by = 4

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def partner(request):
    context = {
        'partners': Partner.objects.all(),
        'articles_support': Article.objects.filter(is_support = True)
    }
    return render(request,'main/partner.html', context)

def support(request):
    return render(request,'main/support.html')

def volo(request):
    return render(request,'main/volo.html')

class FoundLostList(ListView):
    model = Article
    template_name = 'main/foundlost.html'
    paginate_by = 4

    def get_queryset(self):
        qs = super().get_queryset()
        qs = (qs.filter(is_found=True)) | (qs.filter(is_lost=True))
        return qs.order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

main/templates/main/about.html
{% extends "main/base.html" %}

{% block content %}

<div class="parallax parallax_all parallax_top  lg-screen">
</div>

    <div class="main-box text-decor-none regular-text">
        <h2>Stowarzyszenie Mam Głos w Nowym Sączu</h2>
        <hr>
        <p> Staramy się uczynić bardziej kolorowym świat bezdomnych, porzuconych i skrzywdzonych psów. Przywracamy im wiarę w człowieka i pokazujemy, że komuś na nich zależy.</p>
        <p>Pełne brzuchy, zagojone rany, posklejane serca, odzyskane zaufanie do człowieka i szczęście na pyszczku ♥</p>
        <h5></h5><br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-5	col-xl-5">
                <h5>Zapraszamy do odwiedzin:</h5>
                <p>
                    <br>Przytulisko: ul. Asnyka 3, Nowy Sącz
                    <br>Biuro: ul. Marcina Borelowskiego 29, Nowy Sącz
                    <br>tel. 530 994 113
                    <br><a href="https://www.facebook.com/stowarzyszenieMamGlos/">facebook</a>
                    <br>KRS: 0000420018
                    <br>Nr konta: 19 1050 1722 1000 0090 3011 4400
                </p>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-7	col-xl-7">
                <iframe class='address_map' src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2585.616736914441!2d20.6925121518358!3d49.60497657926633!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473de5258e4d858d%3A0xb29d1e2cb9d82e1b!2sAdama%20Asnyka%203%2C%2033-300%20Nowy%20S%C4%85cz!5e0!3m2!1spl!2spl!4v1571306939312!5m2!1spl!2spl" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
        </div>

        <hr>
        <h5> Dokumenty </h5>
        {% for doc in documents %}
        <a href="http://www.mamglos-ns.pl/media/documents/{{ doc.filename }}">{{ doc.filename }}</a>
        {% endfor %}
    </div>

{% endblock content%}

main/templates/main/adopted.html
{% extends 'main/base.html' %}

{% block content %}
<div class="parallax parallax_all parallax_top lg-screen">
</div>

    <div class="main-box text-decor-none regular-text">
        <h2> Pieski, ktore znalazły już swoją ukochaną rodzinę </h2>
        <hr>
    </div>
    <div class="pictures_mosaic">
        {% for dog in object_list %}
        <div class="image-hover-text" data-content1={{ dog.dog_name }} data-content2={{ dog.adoption_date }}>
            <img src="{{ dog.dog_picture.url }}">
        </div>
        {% endfor %}
    </div>

{% endblock content %}

main/templates/main/base.html
{% load static %}

<!DOCTPYE html>

<html lang="en">
<head>
    <title> Stowarzyszenie Mam Głos Nowy Sącz </title>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400,400i&display=swap" rel="stylesheet">

    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Stowarzyszenie Mam Głos w Nowym Sączu">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/styles.css' %}">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'pics/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'pics/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'pics/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'pics/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'pics/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'pics/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'pics/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'pics/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'pics/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'pics/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'pics/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'pics/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'pics/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'pics/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'pics/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
</head>
<body>

<!--navBar-->

<nav class="navbar navbar-expand-xl navbar-light bg-white nav-sticky">
    <a class="navbar-brand" href="{% url 'main-home' %}"><img src="../../static/pics/logoJ1.png" class="logo-size" alt="Mam Głos"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center bg-transparent" id="navbarSupportedContent">
        <div class="navbar-nav">
            {% with url_name=request.resolver_match.url_name %}
            <a class="nav-item nav-link {% if url_name == 'main-home' %}active{% endif %}" href="{% url 'main-home' %}">Home </a>
            <a class="nav-item nav-link {% if url_name == 'main-about' %}active{% endif %}" href="{% url 'main-about' %}">O nas </a>
            <a class="nav-item nav-link {% if url_name == 'main-news' %}active{% endif %}" href="{% url 'main-news' %}">Aktualności</a>
            <a class="nav-item nav-link {% if url_name == 'main-volo' %}active{% endif %}" href="{% url 'main-volo' %}">Wolontariat</a>
            <a class="nav-item nav-link {% if url_name == 'main-forAdoption' %}active{% endif %}" href="{% url 'main-forAdoption' %}"><strong>Potrzebują domu</strong></a>
            <a class="nav-item nav-link {% if url_name == 'main-adopted' %}active{% endif %}" href="{% url 'main-adopted' %}">Mają dom</a>
            <a class="nav-item nav-link {% if url_name == 'main-foundlost' %}active{% endif %}" href="{% url 'main-foundlost' %}">Znalezione/Zagubione</a>
            <a class="nav-item nav-link {% if url_name == 'main-partner' %}active{% endif %}" href="{% url 'main-partner' %}">Darczyńcy</a>
            <a class="nav-item nav-link {% if url_name == 'main-contact' %}active{% endif %}" href="{% url 'main-contact' %}">Kontakt</a>
            {% endwith %}
            <a href="{% url 'main-support' %}" class="btn btn-success color-white xl-screen"> Wesprzyj nas</a>
        </div>
    </div>
</nav>

<div class="nav-margin-custom bg-transparent"></div>
{% block content %}
{% endblock %}

{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item "><a class="page-link color-darkgrey" href="/news?page=1" tabindex="-1"><<< </a></li>
        <li class="page-item "><a class="page-link color-darkgrey" href="/news?page={{ page_obj.previous_page_number }}" tabindex="-1"><</a></li>
        <li class="page-item "><a class="page-link color-darkgrey" href="/news?page={{ page_obj.previous_page_number }}" tabindex="-1">{{ page_obj.previous_page_number }}</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link color-darkgrey" href="#" tabindex="-1"><</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link color-darkgrey" href=""><strong>{{ page_obj.number }}</strong></a></li>
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link color-darkgrey" href="/news?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></a></li>
        <li class="page-item"><a class="page-link color-darkgrey" href="/news?page={{ page_obj.next_page_number }}">></a></li>
        <li class="page-item"><a class="page-link color-darkgrey" href="/news?page={{ page_obj.paginator.num_pages }}"> >>></a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">></a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

<footer class="footer pt-3 dark-green-bg">
    <div class='container m-auto'>
        <div class='row bottom-space'>
            <div class='col-lg-4 col-md-4 col-sm-6 col-xs-12 pt-3 color-light-grey'>
                <h5 class="color-light-grey"> Kontakt </h5>
                ul. Asnyka 3, Nowy Sącz
                <br>tel. 530 994 113
                <br><a href="https://www.facebook.com/stowarzyszenieMamGlos/">facebook</a>
            </div>
            <div class='col-lg-4 col-md-4 col-sm-6 col-xs-12 pt-3 color-light-grey'>
                <h5 class="color-light-grey"> Wsparcie </h5>
                Zachęcamy do wsparcia Stowarzyszenia
                <br>Nr konta: 19 1050 1722 1000 0090 3011 4400
                <br> Przekaż 1% podatku - KRS: 0000420018
            </div>
            <div class='col-lg-4 col-md-4 col-sm-6 col-xs-12 pt-3 color-light-grey'>
                <h5 class="color-light-grey"> Dokumenty </h5>
                Sprawozdanie roczne
                <br>
                <a href="http://www.mamglos-ns.pl/media/documents/umowa_adopcyjna.pdf" target="_blank"> Wzór umowy adopcyjnej </a>
            </div>
        </div>
    </div>
</footer>
<div class="sign dark-green-bg pt-3 text-centered color-light-grey">
    Copyright &copy; <script type="text/javascript">document.write(new Date().getFullYear()); </script> <a class="color-light-grey text-decor-none" href='https://www.iminez.com'>i'm Inez</a>
</div>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<!-- change nav color on scroll -->
<script src="{% static 'main/scroll_color_change.js' %}"></script>

</body>



</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block content %}
<div class="parallax parallax_all parallax_top lg-screen">
</div>

    <div class="main-box text-decor-none regular-text">
        <h2>Kontakt </h2>
        <hr>
            <div class="jumbotron jumbotron-fluid support_jumbo">
                <div class="m-auto px-3">
                    <h1 class="display-4">Prosimy o wsparcie</h1>
                    <p class="lead">Zachęcamy do ustawienia cyklicznego przelewu na nasze konto: <br>
                        <b>19 1050 1722 1000 0090 3011 4400</b><br> nawet 5zł miesięcznie podbuduje nasz budżet!</p>
                    <p class="lead">Zachęcamy rownież do odwiedzenia nas, psiaki będą merdać ogonem za każdy najmniejszy podarunek.</p>
                </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-5	col-xl-5 font-size-p">
                <h5>Zapraszamy do odwiedzin:</h5>
                    <br>Przytulisko: ul. Asnyka 3, Nowy Sącz
                    <br>Biuro: ul. Marcina Borelowskiego 29, Nowy Sącz
                    <br>tel. 530 994 113
                    <br><a href="https://www.facebook.com/stowarzyszenieMamGlos/">facebook</a>
                    <br>KRS: 0000420018
                    <br>Nr konta: 19 1050 1722 1000 0090 3011 4400
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-7	col-xl-7">
                <iframe class='address_map' src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2585.616736914441!2d20.6925121518358!3d49.60497657926633!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473de5258e4d858d%3A0xb29d1e2cb9d82e1b!2sAdama%20Asnyka%203%2C%2033-300%20Nowy%20S%C4%85cz!5e0!3m2!1spl!2spl!4v1571306939312!5m2!1spl!2spl" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
        </div>
    </div>

{% endblock content %}

main/templates/main/forAdoption.html
{% extends 'main/base.html' %}

{% block content %}
<div class="parallax parallax_all parallax_top lg-screen">
</div>


<div class="main-box text-decor-none regular-text">
    <h2>Poznaj nasze psiaki, pokochaj i zabierz do domu!</h2>
    <p> Przedstawiamy psiaki polecające się do adopcji.</p>
    <p>Wszystkie psiaki są zaszczepione, odrobaczone, zaczipowane i wysterylizowane/wykastrowane. Z osobą adoptującą podpisywana jest umowa adopcyjna. Nie wydajemy psów na łańcuch, ani do kojca. Obowiązuje wizyta przed i poadopcyjna !! Szukamy domów 🏡, gdzie psiaki będą pełnoprawnymi członkami rodziny.</p>
    <p>PAMIĘTAJ! Decyzja o adopcji powinna być przemyślana. Pies to nowy członek rodziny, wiążą się z nim obowiązki i koszty na lata, ale też mnóstwo przyjemności i niepowtarzalnych chwil. </p>
    <p>Więcej informacji: <a href="{% url 'main-contact' %}">kontakt</a></p>
    <hr>
</div>

{% for dog in object_list %}
<div class="width-screen-adjust regular-text">
    <div class="row bg-lightgrey">
        <div class='col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 text-centered'>
            <a href='{{ dog.dog_gallery }}'><img src="{{ dog.dog_picture.url }}" class="dogPicture max-width100pr"></a></div>
        <div class='col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6'>
            <h1 class="text-centered mt-3">{{ dog.dog_name }}</h1>
            <p class="px-3">{{ dog.dog_description }}</p>
            <p class="px-3"><a href="{{ dog.dog_gallery }}" target="_blank" rel="noopener noreferrer">Zobacz mój album</a></p></div>
        <a href="{% url "main-contact" %}" class="btn btn-info btnCenter">Chcę poznać</a>
    </div>
</div>
{% endfor %}
{% endblock content %}

main/templates/main/foundlost.html
{% extends 'main/base.html' %}
{% block content %}

<div class="parallax parallax_all parallax_top lg-screen">
</div>

    <div class="main-box text-decor-none regular-text">
        <h2>Ogłoszenia o zwierzętach zaginionych i znalezionych w Nowym Sączu i okolicach</h2>
        <p> Prosimy o <a href="{% url 'main-contact' %}">kontakt</a> na facebooku lub przez mail, by dodać ogłoszenie. </p>
        <hr>

        {% for article in object_list %}

        <div class="jumbotron light-blue-bg">
        <h3 class="display-8">{{ article.title}}</h3>
        <p class="lead">{{ article.date }}</p>
        <p class="lead">{{ article.tldr }}</p>
        {% if article.fb_link %}
        <a href="{{ article.fb_link }}">Zobacz post na facebooku</a>
        {% endif %}
        <hr class="my-4">
        <p>{{ article.article_text }}</p>
        {% for image in article.articlepicture_set.all %}
        <a target="_blank" href="{{ image.image.url }} ">
            <img class="thumbnail_img" src="{{ image.image.url }}"></a>
        {% endfor %}
    </div>
    {% endfor %}

    {% if is_paginated %}

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="/news?page={{ page_obj.previous_page_number }}" tabindex="-1">Poprzednia</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Poprzednia</a>
            </li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="/news?page={{ page_obj.next_page_number }}">Następna</a>
                {% else %}
            <li class="page-item disables">
                <a class="page-link" href="#">Nastepna</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    </div>

{% endblock content %}

main/templates/main/news.html
{% extends 'main/base.html' %}
{% block content %}

<div class="parallax parallax_all parallax_top lg-screen">
</div>
<div class="main-box text-decor-none regular-text">
    <h2>Aktualności</h2>
    <hr>
    {% for article in object_list %}

    <div class="jumbotron light-blue-bg">
        <h3 class="display-8">{{ article.title}}</h3>
        <p class="lead">{{ article.date }}</p>
        <p class="lead">{{ article.tldr }}</p>
        {% if article.fb_link %}
        <a href="{{ article.fb_link }}">Zobacz post na facebooku</a>
        {% endif %}
        <hr class="my-4">
        <p>{{ article.article_text }}</p>
        {% for image in article.articlepicture_set.all %}
        <a target="_blank" href="{{ image.image.url }} ">
            <img class="thumbnail_img" src="{{ image.image.url }}"></a>
        {% endfor %}
    </div>
    {% endfor %}


</div>

{% endblock content %}

main/templates/main/partner.html
{% extends 'main/base.html' %}
{% block content %}

<div class="parallax parallax_all parallax_top lg-screen">
</div>

<div class="main-box text-decor-none regular-text">
    <h2>Podziękowania dla naszych głównych darczyńców </h2>
    <hr>
    <div class="row bottom-space">
        {% for partner in partners %}
        {{ partner.1 }}
        {% if forloop.counter|divisibleby:3 %}
        <div class="card text-centered m-auto no-borders" style="width: 16rem;">
            <a href="{{ partner.thanks_link }}"  >
                <img class="card-img-top" src="{{ partner.logo.url }}" alt="{{ partner.name }}"> </a>
            <div class="card-body partnerCompanyName"></div>
        </div>
    </div>
    <div class="row rowBottomMargin">
        {% else %}
        <div class="card text-centered m-auto no-borders" style="width: 16rem;">
            <a href="{{ partner.thanks_link }}"  >
                <img class="card-img-top" src="{{ partner.logo.url }}" alt="{{ partner.name }}"> </a>
            <div class="card-body partnerCompanyName"></div>
        </div>
        {% endif %}
        {% endfor %}
    </div>

    <h2>Podziękowania za wsparcie Stowarzyszenia</h2>
    <hr>
    {% for article in articles_support %}
    <div class="jumbotron light-blue-bg font-size-p">
        <h1 class="display-8">{{ article.title}}</h1>
        <p class="lead">{{ article.date }}</p>
        <p class="lead">{{ article.tldr }}</p>
        {% if article.fb_link %}
        <a href="{{ article.fb_link }}">Zobacz post na facebooku</a>
        {% endif %}
        <hr class="my-4">
        <p>{{ article.article_text }}</p>
        {% for image in article.articlepicture_set.all %}
        <a target="_blank" href="{{ image.image.url }} ">
            <img class="thumbnail_img" src="{{ image.image.url }}"></a>
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock content %}